version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest # Use a specific version tag in production
    container_name: keycloak-sigil-lock
    environment:
      # --- Keycloak Admin Credentials (for the master realm) ---
      KC_BOOTSTRAP_ADMIN_USERNAME: admin # CHANGE THIS for production
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin # CHANGE THIS for production

      # --- Database Configuration (Using PostgreSQL) ---
      KC_DB: postgres
      KC_DB_URL_HOST: postgres # Service name of the postgres container
      KC_DB_URL_PORT: 5432 # Default postgres port
      KC_DB_DATABASE: keycloak # Must match POSTGRES_DB in postgres service
      KC_DB_USERNAME: keycloak # Must match POSTGRES_USER in postgres service
      KC_DB_PASSWORD: password # Must match POSTGRES_PASSWORD in postgres service
      KC_DB_SCHEMA: public

      # --- HTTP/HTTPS Configuration (for local development) ---
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_PROXY: edge

    ports:
      - "8080:8080"
      - "8443:8443"

    volumes:
      # Mount the realm config for import on first start
      - ./realm-config.json:/opt/keycloak/data/import/realm-config.json:z

    command:
      # Start Keycloak (not -dev mode when using external DB usually) and import
      - start
      - --import-realm

    depends_on:
      - postgres # Ensure postgres starts before keycloak

  postgres:
    image: postgres:15 # Use a specific version
    container_name: postgres-sigil-lock
    volumes:
      - postgres_data:/var/lib/postgresql/data:z # Persist PostgreSQL data
    environment:
      POSTGRES_DB: keycloak # Database name for Keycloak
      POSTGRES_USER: keycloak # Database user for Keycloak
      POSTGRES_PASSWORD: password # Database password for Keycloak
    ports:
      # Optional: Expose postgres port for debugging/direct access
      - "5432:5432"

# Define named volumes
volumes:
  postgres_data: {} # Volume for PostgreSQL data persistence
