defmodule SigilLock.Repo.Migrations.CreateTenants do
  use Ecto.Migration

  def change do
    # Optional: Ensure the uuid-ossp extension is enabled.
    # You might run this manually in psql or include it in an earlier, separate migration
    # if you want to manage it via migrations. Ecto doesn't have a built-in function for extensions.
    # execute "CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";"

    create table(:tenants, primary_key: false) do
      # Define the primary key as UUID, auto-generated by the database
      add :id, :binary_id, primary_key: true

      # Tenant attributes
      add :name, :string, null: false

      # Standard Ecto timestamps
      timestamps()
    end

    # Index for faster lookups by tenant name
    create index(:tenants, [:name])

  end
end
